### ISSUE TITLE
Close files after opening in Molecule

### ISSUE THREAD

**Issue by origamimantis** [leeping/forcebalance#212]
When there are many Molecules being made, eventually an error will be created because there are too many open files.
In my case, I read .xyz files.

Is there a way to close these files?

The error:
Traceback (most recent call last):
  File "minimize_ffs.py", line 745, in <module>
  File "minimize_ffs.py", line 708, in main
  File "minimize_ffs.py", line 474, in min_xtb
  File "minimize_ffs.py", line 505, in align
  File "/data/homezvol2/zhange5/.conda/envs/zhange5-conda/lib/python3.7/site-packages/forcebalance/molecule.py", line 1264, in __init__
  File "/data/homezvol2/zhange5/.conda/envs/zhange5-conda/lib/python3.7/site-packages/forcebalance/molecule.py", line 2868, in read_xyz
  File "/data/homezvol2/zhange5/.conda/envs/zhange5-conda/lib/python3.7/site-packages/forcebalance/molecule.py", line 2889, in read_xyz0
OSError: [Errno 24] Too many open files: 'xtbfull_48.xyz'

**Comment by leeping** [comment]
Strange, I hadn't seen that before. I thought that the file object would close after the loop is finished iterating but maybe not. 
 
Perhaps you could try replacing this line https://github.com/leeping/forcebalance/blob/master/src/molecule.py#L2905 with something like:
```
with open(fnm) as f:
    for line in f:
```

Let me know if that resolves the issue.

**Comment by origamimantis** [comment]
Ok, I replaced those lines and it ended up with the same error (which is strange, I thought it would work).
I ended up working around the issue by adapting or importing the functions I needed.
